version: '2.3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch
    network_mode: host
    volumes:
      - ./elasticsearch/volumes:/usr/share/elasticsearch/data

  kibana:
    build:
      context: ./kibana
    container_name: kibana
    network_mode: host

  logstash:
    build:
      context: ./logstash
    container_name: logstash
    network_mode: host
    volumes:
      - ./logstash/volumes:/usr/share/logstash/data
  
  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    network_mode: "host"