version: '2.3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch
    network_mode: host
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    build:
      context: ./kibana
    container_name: kibana
    network_mode: host
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    build:
      context: ./logstash
    container_name: logstash
    network_mode: host
    volumes:
      - logstash_data:/usr/share/logstash/data
    depends_on:
      elasticsearch:
        condition: service_healthy
  
  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    network_mode: "host"

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    network_mode: "host"
  
  mysql:
    image: mysql:5.6
    container_name: mysql
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_example
  
    
volumes:
  elasticsearch_data:
  logstash_data:
